import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const acidentes = [
  {
    codigo: '01',
    nome: 'LUIZ HENRIQUE RAMOS GOMES',
    cargo: 'MOTORISTA',
    dataAdmissao: new Date('2014-07-14'),
    dataOcorrencia: new Date('2026-01-07'),
    trechoObra: 'PÁTIO',
    mes: 'JAN',
    ano: 2026,
    diasPerdidos: 0,
    tipoAcidente: 'Típico',
    afastamento: 'ACA',
    horarioAcidente: '07:30',
    turno: 'Manhã',
    areaLesionada: 'MÃO',
    situacaoInvestigacao: 'Investigado',
    valoresGastos: null,
    cid: null,
    agenteCausador: 'FERRAMENTA',
  },
  {
    codigo: '02',
    nome: 'JOSE LEAL DOS SANTOS NETO',
    cargo: 'OPERADOR DE MÁQUINAS',
    dataAdmissao: new Date('2014-07-14'),
    dataOcorrencia: new Date('2026-01-14'),
    trechoObra: 'TRECHO 03',
    mes: 'JAN',
    ano: 2026,
    diasPerdidos: 2,
    tipoAcidente: 'Típico',
    afastamento: 'ASA',
    horarioAcidente: '14:00',
    turno: 'Tarde',
    areaLesionada: 'PÉ',
    situacaoInvestigacao: 'Investigado',
    valoresGastos: null,
    cid: null,
    agenteCausador: 'QUEDA',
  },
  {
    codigo: '03',
    nome: 'JORGE LUIZ SILVA',
    cargo: 'VIGIA',
    dataAdmissao: new Date('2019-03-01'),
    dataOcorrencia: new Date('2026-02-11'),
    trechoObra: 'PÁTIO',
    mes: 'FEV',
    ano: 2026,
    diasPerdidos: 0,
    tipoAcidente: 'Típico',
    afastamento: 'ACA',
    horarioAcidente: '22:00',
    turno: 'Noite',
    areaLesionada: 'DEDO',
    situacaoInvestigacao: 'Investigado',
    valoresGastos: null,
    cid: null,
    agenteCausador: 'PORTA',
  },
  {
    codigo: '04',
    nome: 'PAULO SERGIO PIRES',
    cargo: 'MOTORISTA',
    dataAdmissao: new Date('2018-06-04'),
    dataOcorrencia: new Date('2026-02-19'),
    trechoObra: 'TRECHO 01',
    mes: 'FEV',
    ano: 2026,
    diasPerdidos: 15,
    tipoAcidente: 'Típico',
    afastamento: 'ASA',
    horarioAcidente: '10:30',
    turno: 'Manhã',
    areaLesionada: 'OMBRO',
    situacaoInvestigacao: 'Investigado',
    valoresGastos: null,
    cid: null,
    agenteCausador: 'VEÍCULO',
  },
  {
    codigo: '05',
    nome: 'FRANCISCO ALVES DA SILVA',
    cargo: 'AJUDANTE',
    dataAdmissao: new Date('2023-01-10'),
    dataOcorrencia: new Date('2026-02-25'),
    trechoObra: 'TRECHO 02',
    mes: 'FEV',
    ano: 2026,
    diasPerdidos: 0,
    tipoAcidente: 'Típico',
    afastamento: 'ACA',
    horarioAcidente: '08:00',
    turno: 'Manhã',
    areaLesionada: 'JOELHO',
    situacaoInvestigacao: 'Investigado',
    valoresGastos: null,
    cid: null,
    agenteCausador: 'QUEDA',
  },
  {
    codigo: '06',
    nome: 'WELLINGTON MOURA SANTOS',
    cargo: 'OPERADOR DE MÁQUINAS',
    dataAdmissao: new Date('2020-02-17'),
    dataOcorrencia: new Date('2026-03-04'),
    trechoObra: 'TRECHO 04',
    mes: 'MAR',
    ano: 2026,
    diasPerdidos: 30,
    tipoAcidente: 'Típico',
    afastamento: 'ASA',
    horarioAcidente: '09:00',
    turno: 'Manhã',
    areaLesionada: 'COLUNA',
    situacaoInvestigacao: 'Investigado',
    valoresGastos: null,
    cid: null,
    agenteCausador: 'MÁQUINA',
  },
  {
    codigo: '07',
    nome: 'RAIMUNDO NONATO FARIA',
    cargo: 'PEDREIRO',
    dataAdmissao: new Date('2022-05-03'),
    dataOcorrencia: new Date('2026-03-11'),
    trechoObra: 'TRECHO 01',
    mes: 'MAR',
    ano: 2026,
    diasPerdidos: 0,
    tipoAcidente: 'Típico',
    afastamento: 'ACA',
    horarioAcidente: '11:00',
    turno: 'Manhã',
    areaLesionada: 'MÃO',
    situacaoInvestigacao: 'Investigado',
    valoresGastos: null,
    cid: null,
    agenteCausador: 'FERRAMENTA',
  },
  {
    codigo: '08',
    nome: 'ANTONIO CARLOS FERREIRA',
    cargo: 'SERVENTE',
    dataAdmissao: new Date('2024-08-12'),
    dataOcorrencia: new Date('2026-03-18'),
    trechoObra: 'TRECHO 03',
    mes: 'MAR',
    ano: 2026,
    diasPerdidos: 0,
    tipoAcidente: 'Trajeto',
    afastamento: 'ACA',
    horarioAcidente: '06:00',
    turno: 'Manhã',
    areaLesionada: 'PERNA',
    situacaoInvestigacao: 'Investigado',
    valoresGastos: null,
    cid: null,
    agenteCausador: 'VEÍCULO',
  },
  {
    codigo: '09',
    nome: 'MARCOS VINICIUS COSTA',
    cargo: 'AJUDANTE',
    dataAdmissao: new Date('2023-07-24'),
    dataOcorrencia: new Date('2026-04-02'),
    trechoObra: 'TRECHO 02',
    mes: 'ABR',
    ano: 2026,
    diasPerdidos: 5,
    tipoAcidente: 'Típico',
    afastamento: 'ASA',
    horarioAcidente: '15:00',
    turno: 'Tarde',
    areaLesionada: 'TORNOZELO',
    situacaoInvestigacao: 'Em investigação',
    valoresGastos: null,
    cid: null,
    agenteCausador: 'QUEDA',
  },
  {
    codigo: '10',
    nome: 'DANIEL SOUZA LIMA',
    cargo: 'MOTORISTA',
    dataAdmissao: new Date('2021-11-08'),
    dataOcorrencia: new Date('2026-04-10'),
    trechoObra: 'PÁTIO',
    mes: 'ABR',
    ano: 2026,
    diasPerdidos: 0,
    tipoAcidente: 'Típico',
    afastamento: 'ACA',
    horarioAcidente: '13:30',
    turno: 'Tarde',
    areaLesionada: 'CABEÇA',
    situacaoInvestigacao: 'Investigado',
    valoresGastos: null,
    cid: null,
    agenteCausador: 'QUEDA DE OBJETO',
  },
  {
    codigo: '11',
    nome: 'CARLOS ROBERTO MENDES',
    cargo: 'OPERADOR DE MÁQUINAS',
    dataAdmissao: new Date('2017-04-20'),
    dataOcorrencia: new Date('2026-04-22'),
    trechoObra: 'TRECHO 04',
    mes: 'ABR',
    ano: 2026,
    diasPerdidos: 45,
    tipoAcidente: 'Típico',
    afastamento: 'ASA',
    horarioAcidente: '10:00',
    turno: 'Manhã',
    areaLesionada: 'BRAÇO',
    situacaoInvestigacao: 'Em investigação',
    valoresGastos: null,
    cid: null,
    agenteCausador: 'MÁQUINA',
  },
]

const taxas = [
  {
    mes: 'JAN',
    ano: 2026,
    totalEmpregados: 176,
    totalHorasTrabalhadas: 39470.93,
    acidentesComAfastamento: 1,
    acidentesSemAfastamento: 1,
    totalAcidentes: 2,
    diasPerdidos: 2,
    diasDebitados: null,
    totalDiasPerdidos: 2,
    taxaFrequencia: 25.33,
    taxaGravidade: 50.67,
    indiceRelativo: null,
  },
  {
    mes: 'FEV',
    ano: 2026,
    totalEmpregados: 189,
    totalHorasTrabalhadas: 42350.4,
    acidentesComAfastamento: 1,
    acidentesSemAfastamento: 2,
    totalAcidentes: 3,
    diasPerdidos: 15,
    diasDebitados: null,
    totalDiasPerdidos: 15,
    taxaFrequencia: 23.61,
    taxaGravidade: 354.17,
    indiceRelativo: null,
  },
  {
    mes: 'MAR',
    ano: 2026,
    totalEmpregados: 201,
    totalHorasTrabalhadas: 45024.0,
    acidentesComAfastamento: 1,
    acidentesSemAfastamento: 2,
    totalAcidentes: 3,
    diasPerdidos: 30,
    diasDebitados: null,
    totalDiasPerdidos: 30,
    taxaFrequencia: 22.21,
    taxaGravidade: 666.35,
    indiceRelativo: null,
  },
  {
    mes: 'ABR',
    ano: 2026,
    totalEmpregados: 195,
    totalHorasTrabalhadas: 43680.0,
    acidentesComAfastamento: 2,
    acidentesSemAfastamento: 1,
    totalAcidentes: 3,
    diasPerdidos: 50,
    diasDebitados: null,
    totalDiasPerdidos: 50,
    taxaFrequencia: 45.79,
    taxaGravidade: 1144.66,
    indiceRelativo: null,
  },
]

async function main() {
  console.log('Importing accident data...')

  await prisma.acidente.deleteMany()
  await prisma.taxaFrequencia.deleteMany()

  for (const a of acidentes) {
    await prisma.acidente.create({ data: a })
  }
  console.log(`✓ ${acidentes.length} accidents imported`)

  for (const t of taxas) {
    await prisma.taxaFrequencia.create({ data: t })
  }
  console.log(`✓ ${taxas.length} frequency rate records imported`)

  console.log('Done!')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
